# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build Debian package
        # You may pin to the exact commit or the version.
        # uses: dawidd6/action-debian-package@6093a4f3549c0713f7f226313c36c799fd2194bf
        uses: dawidd6/action-debian-package@v1.4.0
        with:
          # Target CPU architecture
          cpu_architecture: # optional, default is amd64
          # Directory where Debian sources are, relative to workspace
          source_directory: # optional, default is ./
          # Directory where build artifacts will be placed, relative to workspace
          artifacts_directory: # optional, default is ./
          # OS distribution name, value from `debian/changelog` is used if not defined
          os_distribution: # optional
